version: '3.8'

services:
  devcontainer:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DISPLAY=
      - PYTHONPATH=/workspace/libs/core:/workspace/libs/computer:/workspace/libs/agent:/workspace/libs/som:/workspace/libs/pylume:/workspace/libs/computer-server:/workspace/libs/mcp-server
      - PYLUME_HOST=host.docker.internal
    command: sleep infinity
    networks:
      - cua-network

  ui-dev:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ../libs/playground:/app:cached
    ports:
      - "3001:3000"
    depends_on:
      - ui-api-dev
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://ui-api-dev:8000
    command: sh -c "yarn install && yarn dev"
    networks:
      - cua-network

  ui-api-dev:
    image: python:3.11-slim-buster
    working_dir: /app
    volumes:
      - ../libs/playground:/app:cached
    ports:
      - "8001:8000"
    command: sh -c "pip install poetry && poetry install && uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - cua-network

networks:
  cua-network:
    driver: bridge