name: Publish @trycua/core to npm

on:
  push:
    tags:
      - "core-v*"

jobs:
  publish:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        working-directory: ./libs/typescript/core
        run: npm ci

      - name: Build package
        working-directory: ./libs/typescript/core
        run: npm run build --if-present

      - name: Publish to npm
        working-directory: ./libs/typescript/core
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
